// cad-taskpane.jsx — the full Task Pane shell + brake-disc scenario data.
// One <TaskPane scenario={...}/> renders any state from a serializable
// block list — the same component instanced per state on the canvas.

const _h = React.createElement;

// macro source lines (syntax-highlighted spans, matching --code colors)
const MACRO = [
  '<span class="c">\' brake_disc.swp — generated by ORYND</span>',
  '<span class="k">Dim</span> swApp <span class="k">As</span> SldWorks.SldWorks',
  '<span class="k">Dim</span> part  <span class="k">As</span> ModelDoc2',
  '',
  '<span class="k">Sub</span> <span class="f">main</span>()',
  '  <span class="k">Set</span> swApp = Application.SldWorks',
  '  <span class="k">Set</span> part = swApp.<span class="f">NewPart</span>',
  '  part.<span class="f">SketchManager</span>.<span class="f">CreateCircle</span> _',
  '    <span class="n">0</span>, <span class="n">0</span>, <span class="n">0</span>, <span class="n">0.16</span>, <span class="n">0</span>, <span class="n">0</span>  <span class="c">\' Ø320</span>',
  '  part.<span class="f">FeatureManager</span>.<span class="f">FeatureExtrusion3</span> _',
  '    <span class="k">True</span>, <span class="k">False</span>, <span class="k">False</span>, _',
  '    <span class="n">0</span>, <span class="n">0</span>, <span class="n">0.026</span>  <span class="c">\' 26mm thick</span>',
  '  <span class="f">CutBoltCircle</span> part, <span class="n">5</span>, <span class="n">0.115</span>  <span class="c">\' 5×Ø14 @ PCD 230</span>',
  '  part.<span class="f">SaveAs3</span> <span class="s">"brake_disc.step"</span>, <span class="n">0</span>, <span class="n">0</span>',
  '<span class="k">End Sub</span>',
];

// ---------- BLOCK RENDERER ----------
function renderBlock(b, i) {
  const C = window.CAD;
  switch (b.t) {
    case 'user':     return _h(C.UserMsg, { key: i, ...b });
    case 'run': {
      // A reopened chat comes back from chat.json, where a function (onOpen /
      // onOpenInFusion, set live while the turn was running) never survived the
      // save — JSON drops it silently. Rebuild it from the raw path fields that
      // DID survive whenever the live handler isn't there (b.onOpen is only
      // present on the turn that's still in memory from this session).
      const onOpen = b.onOpen || (b.filesDir ? () => window.orynd && window.orynd.openPath(b.filesDir) : null);
      const onOpenInFusion = b.onOpenInFusion || ((b.stepPath && window.adsk && window.adsk.fusionSendData)
        ? () => window.adsk.fusionSendData('import', JSON.stringify({ action: 'import_file', path: b.stepPath }))
        : null);
      return _h(window.THINK.RunProgress, { key: i, ...b, onOpen, onOpenInFusion });
    }
    case 'assist':   return _h(C.AssistMsg, { key: i, em: b.em }, b.text);
    case 'sep':      return _h('div', { className: 'tp-time-sep', key: i }, b.label);
    case 'steps':    return _h('div', { key: i, style: { display: 'flex', flexDirection: 'column', gap: 7 } },
                          b.items.map((s, j) => _h(C.StepCard, { key: j, ...s })));
    case 'research': return _h(C.ResearchCard, { key: i, ...b });
    case 'plan':     return _h(C.OperationPlanCard, { key: i, ...b });
    case 'validate': return _h(C.ValidationCard, { key: i, ...b });
    case 'macro':    return _h(C.MacroCard, { key: i, ...b });
    case 'gate':     return _h(C.ApprovalGate, { key: i, ...b });
    case 'exec':     return _h(C.ExecutionCard, { key: i, ...b });
    case 'result':   return _h(C.ResultCard, { key: i, ...b });
    case 'banner':   return _h(C.Banner, { key: i, ...b });
    case 'inspector':return _h(C.SelectionInspector, { key: i, ...b });
    case 'ctxsug':   return _h(C.ContextSuggestions, { key: i, ...b });
    case 'routebadge': return _h('div', { key: i }, _h(C.RouteBadge, { mode: b.mode }));
    case 'clarify':  return _h(C.ClarificationPopover, { key: i, ...b });
    case 'diff':     return _h(C.PlanDiffCard, { key: i, ...b });
    case 'recipe':   return _h(C.MacroRecipeCard, { key: i, ...b });
    case 'savedbanner': return _h('div', { className: 'tp-vbanner valid', key: i },
                          _h(window.CADIcons.CheckCircle, { size: 16 }), 'Saved to My CAD Library');
    default:         return null;
  }
}

// ---------- TASK PANE SHELL ----------
function TaskPane({ scenario }) {
  const C = window.CAD;
  const s = scenario;
  return _h('div', { className: 'tp', style: { width: '100%', height: '100%' } },
    _h('div', { className: 'tp-shell' },
      _h(C.Header, { connection: s.connection, route: s.route }),
      s.timeline !== false && _h(C.Timeline, { active: s.tlActive ?? 0, failedAt: s.tlFail ?? -1 }),
      s.session && _h(C.ChatSessionHeader, { ...s.session }),
      s.empty
        ? _h(C.EmptyState, null)
        : _h('div', { className: 'tp-body' }, (s.blocks || []).map(renderBlock)),
      _h(C.Composer, { mode: s.mode, value: s.composer, route: s.route, sending: s.sending, disabled: s.connection === 'offline', selection: s.selection }),
    ),
  );
}

// reusable user-prompt block for the brake disc
const USER_PROMPT = { t: 'user', text: 'Create a ventilated brake disc, Ø320, for a 5×114.3 hub.', files: [{ kind: 'sketch', name: 'rotor_ref.svg' }] };

// ============================================================
//  SCENARIOS — same screen, different states
// ============================================================
const SCENARIOS = {
  idle: { connection: 'connected', route: 'ORYND', mode: 'Create', timeline: false, empty: true },

  understanding: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 0,
    blocks: [
      USER_PROMPT,
      { t: 'assist', text: 'Reading your request and the attached rotor sketch. I\'ll plan this as a parametric disc — let me confirm the design', em: 'intent.' },
      { t: 'steps', items: [
        { status: 'active', title: 'Understanding design intent', detail: 'Vented rotor · 5-bolt hub · Ø320 outer' },
        { status: 'pending', title: 'Checking whether search context is needed' },
        { status: 'pending', title: 'Building constrained operation plan' },
      ] },
    ],
  },

  searching: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 1,
    blocks: [
      USER_PROMPT,
      { t: 'steps', items: [
        { status: 'done',   title: 'Understood design intent', detail: 'Vented rotor · 5-bolt hub · Ø320 outer' },
        { status: 'active', title: 'Searching reference geometry', detail: 'PCD & bolt patterns for 5×114.3' },
      ] },
      { t: 'research', sources: [
        { title: 'Brake rotor PCD standards', url: 'tech/pcd' },
        { title: '5×114.3 hub spec sheet', url: 'oem/hub' },
      ], facts: ['PCD 114.3 mm, 5 bolts', 'Typical vented thickness 22–28 mm', 'Center bore 67.1 mm'], confidence: 0.86 },
    ],
  },

  planning: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 2,
    blocks: [
      USER_PROMPT,
      { t: 'assist', text: 'Here\'s the constrained plan. Everything maps to runtime-verified commands — review the', em: 'assumptions.' },
      { t: 'plan',
        cmds: ['sketch', 'circle', 'extrude', 'hole', 'pattern', 'fillet', 'export'],
        ops: [
          { title: 'Sketch disc profile on Front plane', dim: 'Ø320 outer · Ø67.1 bore' },
          { title: 'Extrude boss', dim: 'thickness 26 mm' },
          { title: 'Sketch bolt hole', dim: 'Ø14 @ PCD 114.3' },
          { title: 'Circular pattern · 5 instances', dim: 'equal spacing 72°' },
          { title: 'Edge fillet', dim: 'r 2 mm' },
          { title: 'Export STEP', dim: 'brake_disc.step' },
        ],
        assumptions: ['Vane geometry simplified to solid disc for MVP runtime.', 'Center bore 67.1 mm inferred from 5×114.3 hub.'],
        warnings: ['Ventilation vanes are not in the runtime command set — exported as solid.'],
      },
    ],
  },

  preview: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 5,
    blocks: [
      USER_PROMPT,
      { t: 'plan',
        cmds: ['sketch', 'circle', 'extrude', 'hole', 'pattern', 'fillet', 'export'],
        ops: [
          { title: 'Sketch disc profile on Front plane', dim: 'Ø320 outer · Ø67.1 bore' },
          { title: 'Extrude boss', dim: 'thickness 26 mm' },
          { title: 'Circular pattern · 5× Ø14 bolts', dim: 'PCD 114.3 · 72°' },
          { title: 'Edge fillet + export STEP', dim: 'r 2 mm · brake_disc.step' },
        ],
        assumptions: ['Center bore 67.1 mm inferred from 5×114.3 hub.'],
      },
      { t: 'validate', result: 'valid',
        safety: ['No shell calls', 'No network access', 'No delete / filesystem writes', 'No hidden execution'] },
      { t: 'macro', filename: 'brake_disc.swp', lang: 'VBA', lines: MACRO },
      { t: 'gate' },
    ],
  },

  executing: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 6,
    blocks: [
      USER_PROMPT,
      { t: 'sep', label: 'Approved 14:32' },
      { t: 'exec', progress: 64, steps: [
        { status: 'done',   title: 'Created part', detail: 'brake_disc.sldprt' },
        { status: 'done',   title: 'Sketched & extruded disc', detail: 'Ø320 · 26 mm' },
        { status: 'active', title: 'Cutting bolt circle', detail: '5× Ø14 @ PCD 114.3' },
        { status: 'pending', title: 'Applying edge fillet' },
        { status: 'pending', title: 'Exporting STEP' },
      ] },
    ],
  },

  completed: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 8,
    blocks: [
      USER_PROMPT,
      { t: 'sep', label: 'Completed 14:32 · 41s' },
      { t: 'result', files: [
        { name: 'brake_disc.step', size: '2.4 MB', primary: true },
        { name: 'brake_disc.swp', size: '3 KB' },
        { name: 'operation_plan.json', size: '1.8 KB' },
        { name: 'validation_report.md', size: '0.9 KB' },
      ] },
      { t: 'assist', text: 'Done — Ø320 disc with 5×Ø14 bolt circle is in your model and exported to STEP. Want vanes next? I can branch this as a new', em: 'iteration.' },
    ],
  },

  validation_failed: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 3, tlFail: 3,
    blocks: [
      USER_PROMPT,
      { t: 'validate', result: 'failed',
        errors: ['Extrude depth 0 mm — disc thickness is undefined.', 'Bolt Ø14 overlaps Ø67.1 center bore at PCD 80.'],
        warnings: ['Vane geometry not in runtime command set.'],
        safety: ['No shell, network, or delete calls detected'] },
      { t: 'gate', disabled: true },
    ],
  },

  cad_disconnected: {
    connection: 'offline', route: 'ORYND', mode: 'Create', tlActive: 5,
    blocks: [
      { t: 'banner', kind: 'off', title: 'SolidWorks is disconnected',
        text: 'The validated plan and macro are preserved. Reconnect to run — nothing is lost.',
        action: { label: 'Reconnect', icon: window.CADIcons.Plug } },
      USER_PROMPT,
      { t: 'macro', filename: 'brake_disc.swp', lang: 'VBA', lines: MACRO.slice(0, 9) },
      { t: 'gate', disconnected: true },
    ],
  },

  blocked: {
    connection: 'connected', route: 'ORYND', mode: 'Create', tlActive: 5,
    blocks: [
      USER_PROMPT,
      { t: 'banner', kind: 'blocked', title: 'Trial limit reached',
        text: 'You\'ve used today\'s 3 demo builds. Upgrade to Pro for unlimited runs and un-watermarked STEP exports.',
        action: { label: 'Start one-day free trial', icon: window.CADIcons.Spark } },
      { t: 'macro', filename: 'brake_disc.swp', lang: 'VBA', lines: MACRO.slice(0, 9) },
    ],
  },
};

window.TaskPane = TaskPane;
window.SCENARIOS = SCENARIOS;
window.__renderBlock = renderBlock;
